# Generated by Django 5.1.3 on 2025-10-06 05:07

import core.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tenant_company_address_tenant_gstin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='primary_image',
            field=models.ImageField(blank=True, help_text='Main product image (JPG, PNG, WEBP)', null=True, upload_to=core.models.get_product_image_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='po_document',
            field=models.FileField(blank=True, help_text='Upload PO document (PDF, DOCX, XLSX)', null=True, upload_to=core.models.get_po_document_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'xlsx'])]),
        ),
        migrations.AddField(
            model_name='workorder',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CustomerPurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('po_number', models.CharField(max_length=50)),
                ('po_date', models.DateField()),
                ('delivery_required_by', models.DateField(blank=True, null=True)),
                ('po_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('received', 'Received'), ('acknowledged', 'Acknowledged'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='received', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('special_instructions', models.TextField(blank=True)),
                ('po_document', models.FileField(blank=True, help_text='Upload customer PO document', null=True, upload_to=core.models.get_customer_po_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'xlsx'])])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(limit_choices_to={'party_type': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='customer_purchase_orders', to='core.party')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'ordering': ['-po_date'],
                'unique_together': {('tenant', 'customer', 'po_number')},
            },
        ),
        migrations.CreateModel(
            name='CustomerInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('invoice_number', models.CharField(max_length=50)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('invoice_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('paid', 'Paid'), ('partial_paid', 'Partially Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='sent', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('invoice_document', models.FileField(blank=True, help_text='Upload invoice PDF', null=True, upload_to=core.models.get_invoice_document_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(limit_choices_to={'party_type': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.party')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
                ('reference_customer_po', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='core.customerpurchaseorder')),
            ],
            options={
                'ordering': ['-invoice_date'],
                'unique_together': {('tenant', 'invoice_number')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('document_type', models.CharField(choices=[('id_proof', 'ID Proof'), ('address_proof', 'Address Proof'), ('educational', 'Educational Certificate'), ('experience', 'Experience Letter'), ('other', 'Other')], max_length=20)),
                ('document_name', models.CharField(max_length=200)),
                ('document_file', models.FileField(help_text='Upload PDF or Image (JPG, PNG)', upload_to=core.models.get_employee_document_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('expiry_date', models.DateField(blank=True, help_text='For documents like ID cards', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GLJournalArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('journal_number', models.CharField(max_length=30)),
                ('posting_date', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('narration', models.TextField(blank=True)),
                ('total_debit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_credit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(max_length=20)),
                ('original_id', models.IntegerField()),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='GLJournalLineArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('line_number', models.IntegerField()),
                ('account_code', models.CharField(max_length=20)),
                ('cost_center_code', models.CharField(blank=True, max_length=20)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('description', models.TextField(blank=True)),
                ('original_id', models.IntegerField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.gljournalarchive')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentAdvice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('advice_number', models.CharField(blank=True, max_length=50)),
                ('advice_date', models.DateField()),
                ('total_payment_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('advice_document', models.FileField(blank=True, help_text='Upload payment advice document', null=True, upload_to=core.models.get_payment_advice_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(limit_choices_to={'party_type': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='payment_advices', to='core.party')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'ordering': ['-advice_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAdviceInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('amount_mentioned', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customerinvoice')),
                ('payment_advice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paymentadvice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='paymentadvice',
            name='mentioned_invoices',
            field=models.ManyToManyField(related_name='payment_advices', through='core.PaymentAdviceInvoice', to='core.customerinvoice'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to=core.models.get_product_image_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('display_order', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='core.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='gljournalarchive',
            index=models.Index(fields=['tenant', 'journal_number'], name='core_gljour_tenant__ccfea0_idx'),
        ),
        migrations.AddIndex(
            model_name='gljournalarchive',
            index=models.Index(fields=['posting_date'], name='core_gljour_posting_3419d2_idx'),
        ),
        migrations.AddIndex(
            model_name='gljournallinearchive',
            index=models.Index(fields=['journal', 'line_number'], name='core_gljour_journal_826eff_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentadviceinvoice',
            unique_together={('payment_advice', 'invoice')},
        ),
    ]
